name: frontend

on: [push]

jobs:
      
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Install dependencies
      working-directory: ./frontend
      run: | 
        npm install
        
